### ISSUE TITLE
The release v1.2.2 has wrong module name and can not be imported

### ISSUE THREAD

**Issue by bakito** [Virtomize/confluence-go-api#18]
**Describe the bug**
When want to use the module within my on project I get an error when adding this one with module name github.com/virtomize/confluence-go-api.

I get the following error: 

```
go: github.com/virtomize/confluence-go-api@v1.2.2: parsing go.mod:
	module declares its path as: github.com/cseeger-epages/confluence-go-api
	        but was required as: github.com/virtomize/confluence-go-api
```

Having checked the attached zip of the release 1.2.2 it shows a different module name in the go.mod

**To Reproduce**
1. Go create a new go module that is using this library. E.g: the example from the readme page.
2. Have the main fun with go modules enabled.
3. See error

**Expected behavior**
The released module should have the same name as the repository

**Release version**
The version tag of the used version.

**Additional context**
Workaround: use the hash revision from master:

`require github.com/virtomize/confluence-go-api v1.2.3-0.20200822075649-9e2d6e50b9dd`

**Comment by c-seeger** [comment]
@bakito thanks for opening this issue. The project moved a while ago. Ill created a new release version [v1.2.3](https://github.com/Virtomize/confluence-go-api/releases/tag/v1.2.3) with the latest commit.

**Comment by bakito** [comment]
Wow, that was fast.
It works now, thank you very much.

Best Regards,
Marc
