### ISSUE TITLE
Could not resolve type id '' into a subtype of [simple type, class com.atlassian.confluence.api.model.people.Person]

### ISSUE THREAD

**Issue by matthewcummings** [Virtomize/confluence-go-api#26]
**Describe the bug**
When I attempt to create a new page, I receive an HTTP 440, which is failing with a "Could not resolve type id '' into a subtype of [simple type, class com.atlassian.confluence.api.model.people.Person]" error.

I've been digging into this a bit. I suspect that this has something to do with my credentials being managed via an external identity provider (in my case Google).

**To Reproduce**
I'm running code which is identical to https://github.com/Virtomize/confluence-go-api/blob/master/examples/content/content.go#L39

**Expected behavior**
I'd expect the page to be created.

**Release version**
v1.2.7

**Comment by matthewcummings** [comment]
See my PR, this was failing because the Confluence API did not like the empty `export_view`. I added `omitempty` to all of the optional Content fields required by the POST/create method.

**Comment by c-seeger** [comment]
PR merged
