### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by nyarly** [Virtomize/confluence-go-api#28]
**Describe the bug**

I am trying to create a Content like:
```
	page := goconfluence.Content{
		Type:  "page",
		Title: "test",
		Body: goconfluence.Body{
			Storage: goconfluence.Storage{
				Value:          "Test page",
				Representation: "storage",
			},
		},
		Space: goconfluence.Space{
			Key: "Engineering",
		},
		Version: goconfluence.Version{
			Number: 1,
		},
	}
```
With `SetDebug(true)` I get
```
{"statusCode":400,"message":"org.codehaus.jackson.map.JsonMappingException: Could not resolve type id '' into a subtype of [simple type, class com.atlassian.confluence.api.model.people.Person]\n at [Source: com.atlassian.plugins.rest.common.limitrequest.jersey.LimitingRequestFilter$1@4cdbe3c9; line: 1, column: 661] (through reference chain: com.atlassian.confluence.api.model.content.Content[\"version\"]->com.atlassian.confluence.api.model.content.Version[\"by\"])"}
```

After iterating through a bunch of errors like that, filling in a user and timestamps for the Version and History, I arrive at
```

	user, err := api.CurrentUser()
	if err != nil {
		log.Fatal(err)
	}

	timestamp := time.Now().Format("2006-01-02T15:04:05.999-07:00")

	page := goconfluence.Content{
		Type:  "page",
		Title: "JDL test",
		Body: goconfluence.Body{
			Storage: goconfluence.Storage{
				Value:          "Test page",
				Representation: "storage",
			},
		},
		Space: goconfluence.Space{
			Key: "Engineering",
		},
		Version: goconfluence.Version{
			By: *user,
		},
		History: goconfluence.History{
			CreatedBy:   *user,
			CreatedDate: timestamp,
			LastUpdated: goconfluence.LastUpdated{
				By:   *user,
				When: timestamp,
			},
		},
	}
```

and now I get:
```
{"statusCode":400,"data":{"authorized":true,"valid":false,"errors":[{"message":{"translation":"Maximum number of permitted body entries is 1 but found 2: storage, export_view","args":[]}}],"successful":false},"message":"com.atlassian.confluence.api.service.exceptions.BadRequestException: Could not create content with type page"}
```

It seems like the Content gets serialized with both a Storage and ExportView field in the Body, which my Confluence rejects.

**To Reproduce**

See above. That code was essentially pasted into the content example.

**Expected behavior**
A created page.

**Release version**
```
github.com/virtomize/confluence-go-api v1.2.7
```

**Comment by tommymcguiver** [comment]
I'm getting the same error, looking at the error message I suspect the regression was added in https://github.com/Virtomize/confluence-go-api/commit/ccb1df18de769e1592053414cad84d121a3acb17 commit. A History and Links structs was added to the Content Struct. The Version struct was also modified which is included in the Content Struct. The ExportView was added to the Body struct which is included in the Content Struct. I'd say these fields get added to the request which confluence doesn't like. The request and responses seem to be structurally different for that API call.

I can confirm downgrading to v1.2.6 fixes the issue.

**Comment by c-seeger** [comment]
Thank you @nyarly and @tommymcguiver i'll take a look at it.

**Comment by c-seeger** [comment]
I moved out the `export_view` from the original `goconfluence.Body` and added a new `goconfluence.BodyExportView` containing the `export_view` without the `storage`.

Please check if the 1.2.8 now works properly.

**Comment by tommymcguiver** [comment]
Have tested patch and needs a slight modification see #29

**Comment by c-seeger** [comment]
thank you again @tommymcguiver i added your change.
