### ISSUE TITLE
Deleting Content results in JSON unmarshalling error

### ISSUE THREAD

**Issue by leosunmo** [Virtomize/confluence-go-api#35]
When calling `API.DelContent` you get the following error: `"unexpected end of JSON input"` as the delete content API doesn't return a body, only status code 204, "no content".

**Comment by c-seeger** [comment]
Hi @leosunmo thanks for opening an issue for this and fixing it! Your PR looked fine and I already merged it. I'll close this issue here. Feel free to repopen it if any issues arise.

Thank you very much for investing your time into confluence-go-api!
