### ISSUE TITLE
Accept Personal Access Token

### ISSUE THREAD

**Issue by WTIGER001** [Virtomize/confluence-go-api#41]
In order to use a personal access token the library has to add the Authorization: Bearer <token> header instead of the basic auth. I have a pull request that implements this.

**Comment by nmollerup** [comment]
Was merged in https://github.com/Virtomize/confluence-go-api/pull/42

So this issue should be closed.

**Comment by c-seeger** [comment]
thanks @WTIGER001 for opening this and @nmollerup for answering this already.
