### ISSUE TITLE
Search user by key

### ISSUE THREAD

**Issue by WayneSpiteri** [Virtomize/confluence-go-api#45]
**Is your feature request related to a problem? Please describe.**
When i read certain pages on our confluence i get back the ri:user that has a userkey identifier.  In order to retrieve the user i need to be able to search by key instead of username and accountId

**Describe the solution you'd like**
To support this, in the user.go file change this 

	if strings.Contains(query, ":") {
		data.Set("accountId", strings.Split(query, ":")[1])
	} else {
		data.Set("username", query)
	}

to this

	if strings.Contains(query, ":") {
		customLookup := strings.Split(query, ":")
		if customLookup[0] == "key" {
			data.Set("key", customLookup[1])
		} else {
			data.Set("accountId", customLookup[1])
		}
	} else {
		data.Set("username", query)
	}

**Comment by c-seeger** [comment]
thanks @WayneSpiteri for opening the issue here a while ago it. I fixed this already in 
https://github.com/Virtomize/confluence-go-api/commit/24984bdbfd10112259ea66e6231cc6ed70f7eb57
and close this one.
