### ISSUE TITLE
GetAttachments incorrect return type

### ISSUE THREAD

**Issue by Scapal** [Virtomize/confluence-go-api#50]
**Describe the bug**
When I use GetAttachments on our Confluence Datacenter servers 7.19, the return doesn't match the `Search` structure due to `Search.Results` not matching what is actually received in the json.
If I change `Search.Results` field type from `[]Results` to `[]Content` (along with `results` in content.go@199), then I get the correct content.

**Release version**
I used v1.4.1

**Comment by c-seeger** [comment]
Thank you @Scapal for bringing this up, I will take a look into the current documentation and provide a fix.

**Comment by Scapal** [comment]
Hi @c-seeger,
Thank you for the very quick fix.
You shouldn't have changed the json field name though.
This is working: 
``` 
type Search struct {
	Results   []Content `json:"content"`
```

**Comment by c-seeger** [comment]
@Scapal according to
https://docs.atlassian.com/ConfluenceServer/rest/8.0.0-m90/#api/content-search
`json:"content"` is correct right? 
https://github.com/Virtomize/confluence-go-api/blob/f1ecc79298ce670f62a5edd259152f1541e81480/search.go#L11
so everything should be fine or did I overlooked sth.

If i find some time I need to refactor the tests and add the correct JSON results from the docs.

**Comment by Scapal** [comment]
@c-seeger as you can see in a previous release of the doc, the schema says `content` but the example says `results`: https://docs.atlassian.com/ConfluenceServer/rest/6.9.1/#content/{id}/child/attachment-getAttachments

I copy/pasted too quickly in my previous message, the version working for our 2 Confluence server (v7.19) is:
```
type Search struct {
	Results   []Content `json:"results"`
```

I also had to add the `When` field in `Version` :
```
type Version struct {
	Number    int    `json:"number"`
	MinorEdit bool   `json:"minorEdit"`
	Message   string `json:"message,omitempty"`
	By        *User  `json:"by,omitempty"`
	When      string `json:"when,omitempty"`
}
```

**Comment by c-seeger** [comment]
added Content and Result to have compatibility for v7 and v8
